baseurl = "https://doowonee.com"
languageCode = "ko"
DefaultContentLanguage = "ko"
paginate = 5
title = "Doowonee"
disqusShortname = "doowonee"

[permalinks]
    page = "/:slug/"
    
[params]
    mainSections = ["post"]
    featuredImageField = "image"
    rssFullContent = true
    
    [params.dateFormat]
        published = "Jan 02, 2006"
        lastUpdated = "Jan 02, 2006 15:04 MST"
        
    [params.sidebar]
        emoji = "🍥"
        avatar = "img/avatar.png"
        subtitle = "Software Engineer"
        
    [params.article]
        math = false
        [params.article.license]
            enabled = true 
            default = "Licensed under CC BY-NC-SA 4.0"
            
    [params.comments]
        enabled = true
        provider = "disqus"         # Available: disqus, utterances    
        [params.comments.utterances]
            repo = ""
            issueTerm = "pathname"
            label = ""             # Optional
            theme = "preferred-color-scheme"
            
    [params.widgets]
        enabled = ['archives', 'tag-cloud']
        [params.widgets.archives]
            limit = 5
            ### Archives page relative URL
            path = "archives"       
        [params.widgets.tagCloud]
            limit = 10
            
    [params.opengraph]
        [params.opengraph.twitter]
            site = ""
            card = "summary_large_image"
            
    [params.defaultImage]
        [params.defaultImage.opengraph]
            enabled = false
            local = false
            src = ""
            
[menu]
    [[menu.main]]
        identifier = "home"
        pre = "home"
        name = "Home"
        url = "/"
        weight = 1
    # [[menu.main]]
    #     identifier = "about"
    #     pre = "user"
    #     name = "About"
    #     url = "about"
    #     weight = 3
    [[menu.main]]
        identifier = "archives"
        pre = "archives"
        name = "Archives"
        url = "archives"
        weight = 4
    [[menu.main]]
        identifier = "pinktalkNotice"
        pre = "speakerphone"
        name = "pinktalk notice"
        url = "tags/pinktalk-notice/"
        weight = 3

[related]
    includeNewer = true
    threshold = 60
    toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 200

[markup]
    [markup.highlight]
        noClasses = false
